[package]
name = "timfmt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.6"
grep-cli = "0.1.6"
pad = "0.1.6"
regex = "1.5.4"
